config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :skills

  # Students
  resources :section_preferences
  resources :experiences

  # Instructors
  resources :sections do
    resources :student_preferences
    resources :requirements
  end

  namespace :administrator do
    resources :departments
    resources :courses
    resources :sections
    resources :users
    resources :assignments

    get 'settings' => 'settings#index'
    post 'settings/current_term' => 'settings#set_current_term'
    get 'settings/section_preferences' => 'settings#section_preferences'
    get 'settings/student_preferences' => 'settings#student_preferences'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :set_password, on: :create

  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:google_oauth2]

  has_many :student_preferences, foreign_key: "instructor_id"
  has_many :section_preferences, foreign_key: "student_id"
  has_many :experiences, ->{ joins(:skill) }, foreign_key: "student_id"
  has_many :sections, foreign_key: "cc_instructor_tag", primary_key: "cc_instructor_tag"

  def self.instructors
    where(cc_instructor_tag: Section.select(:cc_instructor_tag).with_current_term)
  end

  def self.students
    where.not(cc_instructor_tag: Section.select(:cc_instructor_tag).with_current_term)
  end

  def self.gtas
    students.where('fte > 0')
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data["email"]).first
    unless user
      user = User.create({
        first_name: data["first_name"],
        last_name: data["last_name"],
        email: data["email"],
        cc_instructor_tag: "#{data["last_name"]}, #{data["first_name"][0]}."
      })
    end
    user
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def is_student
    self.sections.with_current_term.length == 0
  end

  def is_instructor
    self.sections.with_current_term.length > 0
  end

  def role
    if is_student
      "Student"
    elsif is_instructor
      "Instructor"
    elsif is_administrator
      "Administrator"
    end
  end

  private

    def set_password
      self.password = Devise.friendly_token[0,20]
    end
end

app/controllers/administrator/assignments_controller.rb
require 'integer_linear_program'

module Administrator
  class AssignmentsController < BaseController
    before_action :set_students, only: [:new, :create, :edit, :update, :show]
    before_action :set_sections, only: [:new, :create, :edit, :update, :show]

    def index
      @assignments = Assignment.order(created_at: :desc)
    end

    def new
      @assignment = Assignment.new
      @assignments_fte = {}
      @assignments_is_fixed = {}
    end

    def edit
      @assignment = Assignment.find(params[:id])
      @assignments_fte = @assignment.assignments_fte
      @assignments_is_fixed = @assignment.assignments_is_fixed
    end

    def create
      @assignments_fte = params[:assignments_fte] || {}
      @assignments_is_fixed = params[:assignments_is_fixed] || {}

      if params[:commit] == "Run solver"
        begin
          problem = ::IntegerLinearProgram.new(@students, @sections, @assignments_fte, @assignments_is_fixed)
          problem.solve
          @assignments_fte = problem.results
        rescue RuntimeError
          flash[:alert] = "Infeasible solution"
        end
      end

      @assignment = Assignment.create(
        assignments_fte: @assignments_fte, assignments_is_fixed: @assignments_is_fixed)
      redirect_to administrator_assignment_path(@assignment)
    end

    def update
      @assignments_fte = params[:assignments_fte] || {}
      @assignments_is_fixed = params[:assignments_is_fixed] || {}

      if params[:commit] == "Run solver"
        begin
          problem = ::IntegerLinearProgram.new(@students, @sections, @assignments_fte, @assignments_is_fixed)
          problem.solve
          @assignments_fte = problem.results
        rescue RuntimeError
          flash[:alert] = "Infeasible solution"
        end
      end

      @assignment = Assignment.create(
        assignments_fte: @assignments_fte, assignments_is_fixed: @assignments_is_fixed)
      redirect_to administrator_assignment_path(@assignment)
    end

    def show
      @assignment = Assignment.find(params[:id])
      @assignments_fte = @assignment.assignments_fte
      @assignments_is_fixed = @assignment.assignments_is_fixed

      respond_to do |format|
        format.html
        format.txt  { render 'show.txt.erb' }
        format.xlsx { render xlsx: 'show.xlsx.axlsx' }
      end
    end

    private

    def set_students
      @students = User.includes([{section_preferences: :section}, :experiences]).gtas
    end

    def set_sections
      @sections = Section.includes(
        {course: [:requirements, :department]},
        {instructor: :student_preferences}, :section_preferences)
        .with_current_term
        .where('current_enrollment >= ?', 25)
    end
  end
end

app/controllers/administrator/base_controller.rb
module Administrator
  class BaseController < ::ApplicationController
    before_filter :authenticate
    before_filter :authorize

    def authenticate
      unless signed_in?
        return redirect_to root_path, alert: "Must be logged in."
      end
    end

    def authorize
      unless current_user.is_administrator
        return redirect_to root_path, alert: "Must be an administrator."
      end
    end
  end
end

app/controllers/administrator/settings_controller.rb
module Administrator
  class SettingsController < BaseController
    def index
      @terms = Section.select("DISTINCT term").map { |s| [s.term, s.term] }
    end

    def set_current_term
      Setting.current_term = params[:current_term]
      redirect_to administrator_settings_path
    end

    def section_preferences
      @students = User.gtas
      @sections = Section.includes(:section_preferences).with_current_term

      respond_to do |format|
        format.xlsx
      end
    end

    def student_preferences
      @students = User.gtas
      @sections = Section.includes(:section_preferences).with_current_term

      respond_to do |format|
        format.xlsx
      end
    end
  end
end

app/controllers/administrator/users_controller.rb
module Administrator
  class UsersController < BaseController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /admin/users
    def index
      @users = User.all
    end

    # GET /admin/users/1
    def show
    end

    # GET /admin/users/new
    def new
      @user = User.new
    end

    # GET /admin/users/1/edit
    def edit
    end

    # POST /admin/users
    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to administrator_user_path(@user), notice: 'User was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/users/1
    def update
      if @user.update(user_params)
        redirect_to administrator_user_path(@user), notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/users/1
    def destroy
      @user.destroy
      redirect_to administrator_users_url, notice: 'User was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def user_params
        params[:user].permit(:first_name, :last_name, :email, :cc_instructor_tag, :is_administrator, :fte)
      end
  end
end

app/controllers/administrators/assignment_controller.rb
module Administrators
  class AssignmentController < BaseController

    def index
      # @students = User.where(role: "student")
      # @instructos = User.where(role: "instructor")
      
      @sections = [
        "CS 101", "CS 102", "CS 103", "CS 104", "CS 105", 
        "CS 106", "CS 107", "CS 108", "CS 109", "CS 110",
        "CS 101", "CS 102", "CS 103", "CS 104", "CS 105", 
        "CS 106", "CS 107", "CS 108", "CS 109", "CS 110",
        "CS 101", "CS 102", "CS 103", "CS 104", "CS 105", 
        "CS 106", "CS 107", "CS 108", "CS 109", "CS 110",
      ]
      @students = ["Jonah George", "Katie Gifford",  "Ty Skelton", "Tyler Hoppe",
        "JJ Carlos", "John Bourgeious", "Michael McDonald"]
    end

  end
end

app/controllers/administrators/base_controller.rb
module Administrators
  class BaseController < ::ApplicationController
    before_filter :authenticate
    before_filter :authorize

    def synchronize
      CourseCatalogSyncJob.perform_later
      redirect_to root_path
    end

    def authenticate
      unless signed_in?
        return redirect_to root_path, alert: "Must be logged in."
      end
    end

    def authorize
      unless current_user.role == "Administrator"
        return redirect_to root_path, alert: "Must be an administrator."
      end
    end
  end
end

app/controllers/administrators/pages_controller.rb
module Administrators
  class PagesController < BaseController
    def settings
    end
  end
end

app/controllers/administrators/reports_controller.rb
module Administrators
  class ReportsController < BaseController

    def student_preferences
      @students = Student.all
      @department = Department.find_by_subject_code("CS")

      respond_to do |format|
        format.xlsx
      end
    end

    def instructor_preferences
      @instructors = Instructor.all

      respond_to do |format|
        format.xlsx
      end
    end

  end
end

app/controllers/administrators/users_controller.rb
module Administrators
  class UsersController < BaseController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /admin/users
    def index
      @users = User.all
    end

    # GET /admin/users/1
    def show
    end

    # GET /admin/users/new
    def new
      @user = User.new
    end

    # GET /admin/users/1/edit
    def edit
    end

    # POST /admin/users
    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to administrators_user_path(@user), notice: 'User was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/users/1
    def update
      if @user.update(user_params)
        redirect_to administrators_user_path(@user), notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/users/1
    def destroy
      @user.destroy
      redirect_to administrators_users_url, notice: 'User was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def user_params
        params[:user].permit(:name, :email, :role)
      end
  end
end

app/controllers/students/users_controller.rb
module Students
  class UsersController < BaseController
    before_action :set_user, only: [:show, :edit, :update]

    def show
    end

    def edit
    end

    def update
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def user_params
        params[:user].permit(:name)
      end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/administrator/users/_form.html.erb
<%= form_for [:administrator, @user] do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Email</label>
    <%= f.email_field :email, class: "form-control" %>
    <span class="help-block">This email <strong>must</strong> be of the form <code>@oregonstate.edu</code> and match this user's ONID username. Failure to follow this convention will result in data synchronization errors.</span>
  </div>

  <div class="form-group">
    <label>CcInstructorTag</label>
    <%= f.text_field :cc_instructor_tag, class: "form-control" %>
    <span class="help-block">This field <strong>must</strong> be of the form <code>[Last Name], [First Initial].</code>. Failure to follow this convention will result in data synchronization errors.</span>
  </div>

  <div class="form-group">
    <div class="checkbox">
      <label>
        <%= f.check_box :is_administrator %> User Is An Administrator
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :fte %>
    <%= f.number_field :fte, step: 0.01, min: 0, max: 0.50, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit nil, class: "btn btn-default" %>

    <% unless @user.new_record? %>
      <%= link_to "Delete", administrator_user_path(@user), method: :delete,
        data: {confirm: "Are you sure?"}, class: "btn btn-danger pull-right" %>
    <% end %>
  </div>
<% end %>

app/views/administrator/users/_user.html.erb
<tr>
  <td><%= link_to user.id, administrator_user_path(user) %></td>
  <td><%= link_to user.first_name, administrator_user_path(user) %></td>
  <td><%= link_to user.last_name, administrator_user_path(user) %></td>
  <td><%= user.email %></td>
  <td><%= user.role %></td>
  <td><%= user.fte %></td>
</tr>

app/views/administrator/users/edit.html.erb
<%= link_to "&larr; Back to Users".html_safe, administrator_users_path %>

<h1>Editing User</h1>

<%= render 'form' %>

app/views/administrator/users/index.html.erb
<%= link_to "&larr; Back to Settings".html_safe, administrator_settings_path %>

<h2>Users</h2>

<%= link_to "New User", new_administrator_user_path, class: "btn btn-success" %>

<br>

<table class="table">
  <thead>
    <th>Id</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Role</th>
    <th>FTE</th>
  </thead>

  <tbody>
    <%= render @users %>
  </tbody>
</table>

app/views/administrator/users/new.html.erb
<%= link_to "&larr; Back to Users".html_safe, administrator_users_path %>

<h1>New User</h1>

<%= render 'form' %>

app/views/administrator/users/show.html.erb
<%= link_to "&larr; Back to Users".html_safe, administrator_users_path %>

<div class="row">
  <div class="form-group">
    <label class="col-sm-2 control-label">First Name</label>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @user.first_name %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Last Name</label>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @user.last_name %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @user.email %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Role</label>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @user.role %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">FTE</label>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @user.fte %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Administrator</label>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @user.is_administrator ? "Yes" : "No" %></p>
    </div>
  </div>
</div>

<% if @user.is_student %>
  <h4>Experience</h4>
  <ul class="list-group">
    <% @user.experiences.each do |experience| %>
      <li class="list-group-item">
        <span class="label label-primary"><%= experience.value %></span>
        <%= experience.skill.name %>
      </li>
    <% end %>
  </ul>

  <h4>Section Preferences</h4>
  <ul class="list-group">
    <% @user.section_preferences.each do |section_preference| %>
      <li class="list-group-item">
        <span class="label label-primary"><%= section_preference.value %></span>
        <%= section_preference.section.course.label %>
        (<%= section_preference.section.cc_instructor_tag %>)
      </li>
    <% end %>
  </ul>
<% end %>

<% if @user.is_instructor %>
  <h4>Student Preferences</h4>
  <ul class="list-group">
    <% @user.student_preferences.each do |student_preference| %>
      <li class="list-group-item">
        <h4 class="list-group-item-heading"><%= student_preference.student.full_name %></h4>
        <p class="list-group-item-text"><%= student_preference.section.course.label %></p>
        <p class="list-group-item-text">
          <span class="label label-primary"><%= student_preference.value %></span>
        </p>
      </li>
    <% end %>
  </ul>

  <h4>Sections</h4>
  <ul class="list-group">
    <% @user.sections.each do |section| %>
      <div class="list-group-item">
        <h5 class="list-group-item-heading"><%= section.course.name %></h5>
        <p class="list-group-item-text">
        <span class="label label-warning"><%= section.term %></span>
        <span class="label label-primary"><%= section.location %></span>
        <span class="label label-success"><%= "#{section.current_enrollment} / #{section.max_enrollment} students" %></span>
        </p>
      </div>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_administrator_user_path(@user), class: "btn btn-default" %>
<%= link_to 'Back', administrator_users_path, class: "btn btn-default" %>