config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :skills

  # Students
  resources :section_preferences
  resources :experiences

  # Instructors
  resources :sections do
    resources :student_preferences
    resources :requirements
  end

  namespace :administrator do
    resources :departments
    resources :courses
    resources :sections
    resources :users
    resources :assignments

    get 'settings' => 'settings#index'
    post 'settings/current_term' => 'settings#set_current_term'
    get 'settings/section_preferences' => 'settings#section_preferences'
    get 'settings/student_preferences' => 'settings#student_preferences'
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  self.inheritance_column = :_type_disabled

  enum type: {
    :"Hard skill"     => 0,
    :"Lab experience" => 1
  }

  validates_presence_of :type
  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :experiences, dependent: :destroy
end

app/models/students/skill.rb
module Students
  class Skill < ActiveRecord::Base
    self.table_name = "student_skills"

    enum value: {
      :"Qualified"          => 2,
      :"Slightly qualified" => 1,
      :"Unqualified"        => 0,
    }

    validates_uniqueness_of :student_id, scope: [:skill_id]

    validates_presence_of :student_id
    validates_presence_of :skill_id
    validates_presence_of :value

    belongs_to :skill, class_name: "::Skill"
    belongs_to :student
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:edit, :update, :destroy]

  def index
    @skills = Skill.all
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)

    if @skill.save
      if params[:redirect]
        redirect_to params[:redirect], notice: 'Skill was successfully created.'
      else
        redirect_to skills_path, notice: 'Skill was successfully created.'
      end
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @skill.update(skill_params)
      redirect_to skills_path, notice: 'Skill was successfully updated.'
    else
      render "edit"
    end
  end

  def destroy
    @skill.destroy
    redirect_to skills_path, notice: 'Skill was successfully destroyed.'
  end

  private

  def skill_params
    params[:skill].permit(:name, :type)
  end

  def set_skill
    @skill = Skill.find(params[:id])
  end

end

app/controllers/students/skills_controller.rb
module Students
  class SkillsController < BaseController
    before_action :set_skill, only: [:show, :destroy]

    def index
      @skills = current_user.skills
    end

    def new
      @skill = current_user.skills.new
    end

    def create
      @skill = current_user.skills.new(skill_params)

      if @skill.save
        redirect_to students_skills_path, notice: 'Skill was successfully created.'
      else
        render :new
      end
    end

    def destroy
      @skill.delete
      redirect_to students_skills_path, notice: 'Skill was successfully destroyed.'
    end

    private

      def set_skill
        @skill = Skill.find(params[:id])
      end

      def skill_params
        params[:students_skill].permit(:skill_id, :value)
      end
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= form_for @skill do |f| %>

  <% if params[:redirect] %>
    <%= hidden_field_tag :redirect, params[:redirect] %>
  <% end %>

  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@skill.errors.count, "error") %>
        prohibited this skill from being saved:
      </h2>
      <ul>
        <% @skill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "control-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :type, class: "control-label" %>
    <% Skill.types.each do |key, value| %>
      <div class="radio">
        <label>
          <%= f.radio_button :type, key %> <%= key %>
        </label>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-default" %>

    <% if params[:redirect] %>
      <%= link_to 'Back', params[:redirect], class: "btn btn-default" %>
    <% else %>
      <%= link_to 'Back', skills_path, class: "btn btn-default" %>
    <% end %>

    <% unless @skill.new_record? %>
      <%= link_to "Delete", skill_path(@skill), method: :delete,
        class: "btn btn-danger pull-right", rel: "nofollow",
        data: { confirm: "Are you sure? This will delete all associated student experience records as well." } %>
    <% end %>
  </div>

<% end %>

app/views/skills/_skill.html.erb
<%= link_to edit_skill_path(skill), class: "list-group-item" do %>
  <%= skill.name %>
<% end %>

app/views/skills/edit.html.erb
<h2>Edit Skill</h2>

<%= render "form" %>

app/views/skills/index.html.erb
<h2>Skills</h2>

<% if @skills.empty? %>
  <div class="well">No skills found.</div>
<% else %>
  <div class="list-group">
    <%= render @skills %>
  </div>
<% end %>

<%= link_to "Add a skill", new_skill_path, class: "btn btn-default" %>

app/views/skills/new.html.erb
<h2>New Skill</h2>

<%= render "form" %>