config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :skills

  # Students
  resources :section_preferences
  resources :experiences

  # Instructors
  resources :sections do
    resources :student_preferences
    resources :requirements
  end

  namespace :administrator do
    resources :departments
    resources :courses
    resources :sections
    resources :users
    resources :assignments

    get 'settings' => 'settings#index'
    post 'settings/current_term' => 'settings#set_current_term'
    get 'settings/section_preferences' => 'settings#section_preferences'
    get 'settings/student_preferences' => 'settings#student_preferences'
  end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  self.table_name  = 'problems'
end

app/models/course.rb
class Course < ActiveRecord::Base
  default_scope { order(course_number: :asc) }

  belongs_to :department
  has_many :sections
  has_many :requirements

  def label
    "#{department.subject_code} #{course_number}"
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :courses
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  enum value: {
    :"Qualified"          => 2,
    :"Slightly qualified" => 1,
    :"Unqualified"        => 0,
  }

  validates_uniqueness_of :student_id, scope: [:skill_id]

  validates_presence_of :student_id
  validates_presence_of :skill_id
  validates_presence_of :value

  belongs_to :skill
  belongs_to :student, class_name: "User"
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  enum value: {
    :"Qualified"          => 2,
    :"Slightly qualified" => 1,
    :"Unqualified"        => 0,
  }

  validates_uniqueness_of :skill_id, scope: [:course_id]

  validates_presence_of :skill_id
  validates_presence_of :course_id
  validates_presence_of :instructor_id
  validates_presence_of :value

  belongs_to :skill
  belongs_to :course
  belongs_to :instructor
end

app/models/section.rb
class Section < ActiveRecord::Base
  self.inheritance_column = nil

  enum location: {
    :"On campus" => 0,
    :"Ecampus"   => 1
  }

  scope :with_current_term, -> { where(term: Setting.current_term) }

  belongs_to :instructor, class_name: "User",
    foreign_key: "cc_instructor_tag", primary_key: "cc_instructor_tag"
  belongs_to :course
  has_many :student_preferences
  has_many :section_preferences
end

app/models/section_preference.rb
class SectionPreference < ActiveRecord::Base
  enum value: {
    :"Favor"             => 4,
    :"Slightly favor"    => 3,
    :"Neutral"           => 2,
    :"Slightly disfavor" => 1,
    :"Disfavor"          => 0,
  }

  def value_raw
    read_attribute('value')
  end

  scope :with_current_term, -> {
    joins(:section).where(sections: { term: Setting.current_term })
  }

  validates_uniqueness_of :student_id, scope: [:section_id]

  validates_presence_of :student_id
  validates_presence_of :section_id
  validates_presence_of :value

  belongs_to :section
  belongs_to :student, class_name: "User"
end

app/models/setting.rb
class Setting < RailsSettings::CachedSettings
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  self.inheritance_column = :_type_disabled

  enum type: {
    :"Hard skill"     => 0,
    :"Lab experience" => 1
  }

  validates_presence_of :type
  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :experiences, dependent: :destroy
end

app/models/student_preference.rb
class StudentPreference < ActiveRecord::Base
  enum value: {
    :"Favor"             => 4,
    :"Slightly favor"    => 3,
    :"Neutral"           => 2,
    :"Slightly disfavor" => 1,
    :"Disfavor"          => 0,
  }

  def value_raw
    read_attribute('value')
  end

  validates_uniqueness_of :student_id, scope: [:section_id, :instructor_id]

  validates_presence_of :instructor_id
  validates_presence_of :section_id
  validates_presence_of :student_id
  validates_presence_of :value

  belongs_to :instructor, class_name: "User"
  belongs_to :student, class_name: "User"
  belongs_to :section
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :set_password, on: :create

  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:google_oauth2]

  has_many :student_preferences, foreign_key: "instructor_id"
  has_many :section_preferences, foreign_key: "student_id"
  has_many :experiences, ->{ joins(:skill) }, foreign_key: "student_id"
  has_many :sections, foreign_key: "cc_instructor_tag", primary_key: "cc_instructor_tag"

  def self.instructors
    where(cc_instructor_tag: Section.select(:cc_instructor_tag).with_current_term)
  end

  def self.students
    where.not(cc_instructor_tag: Section.select(:cc_instructor_tag).with_current_term)
  end

  def self.gtas
    students.where('fte > 0')
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data["email"]).first
    unless user
      user = User.create({
        first_name: data["first_name"],
        last_name: data["last_name"],
        email: data["email"],
        cc_instructor_tag: "#{data["last_name"]}, #{data["first_name"][0]}."
      })
    end
    user
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def is_student
    self.sections.with_current_term.length == 0
  end

  def is_instructor
    self.sections.with_current_term.length > 0
  end

  def role
    if is_student
      "Student"
    elsif is_instructor
      "Instructor"
    elsif is_administrator
      "Administrator"
    end
  end

  private

    def set_password
      self.password = Devise.friendly_token[0,20]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GtaAssignment</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    
    <%= render "shared/navbar" %>

    <div class="container">
      <% if notice %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1>GtaAssignment</h1>
  <p>The automated system for assigning graduate teaching assistants to classes.</p>
</div>

<div class="col-sm-9">
  <h4>About</h4>

  <p>
    This is an OSU Computer Science Senior Design project based around the idea of
    automating the process of selecting graduate teaching assistants (GTA) for classes.
    Our goal is to save time for the faculty administrators and help both instructors and
    GTAs get the assignments they want. Our application is currently still in beta,
    so thank you ahead of time for helping iron out any issues.
  </p>
  <p>
    If you happen to find a bug or have a suggestion, please don't hesistate to reach out.
  </p>

  <br>

  <h4>Learn More</h4>
  <p>
    This project uses an Integer Linear Program (ILP) to optimally match GTAs to classes.
    By adding GTA and Instructor preferences as factors in the objective function
    and using required skills and GTA experience as constraints, we can find an optimal solution.
  </p>

  <p>
    The interface that you are currently interacting with is a Ruby on Rails application
    that is used for data entry and manipulating the ILP. To reduce the amount of manual data
    entry, it automatically pulls data from ONID and the OSU Course Catalog.
  </p>

  <a href="https://github.com/jonahgeorge/gta-assignment">Source Code</a>
</div>

<div class="col-sm-3">
  <h4>Team</h4>

  <ul>
    <li><a href="mailto:georgej@oregonstate.edu">Jonah George</a></li>
    <li><a href="mailto:graysmar@oregonstate.edu">Ryan Graysmark</a></li>
    <li><a href="mailto:vanzankr@oregonstate.edu">Kris Van Zandt</a></li>
  </ul>

  <br>

  <h4>Customer</h4>

  <ul>
    <li><a href="http://web.engr.oregonstate.edu/~tadepall/">Prasad Tadepalli</a></li>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "GtaAssignment", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <% if current_user.is_instructor %>
            <li><%= link_to "Sections", sections_path %></li>
          <% end %>
          <% if current_user.is_student %>
            <li><%= link_to "Section Preferences", section_preferences_path %></li>
            <li><%= link_to "Experience", experiences_path %></li>
          <% end %>
          <% if current_user.is_administrator %>
            <li><%= link_to "Assignments", administrator_assignments_path %></li>
            <li><%= link_to "Settings", administrator_settings_path %></li>
          <% end %>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", user_omniauth_authorize_path(:google_oauth2) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>