config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :skills

  # Students
  resources :section_preferences
  resources :experiences

  # Instructors
  resources :sections do
    resources :student_preferences
    resources :requirements
  end

  namespace :administrator do
    resources :departments
    resources :courses
    resources :sections
    resources :users
    resources :assignments

    get 'settings' => 'settings#index'
    post 'settings/current_term' => 'settings#set_current_term'
    get 'settings/section_preferences' => 'settings#section_preferences'
    get 'settings/student_preferences' => 'settings#student_preferences'
  end
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  self.table_name  = 'problems'
end

app/controllers/administrator/assignments_controller.rb
require 'integer_linear_program'

module Administrator
  class AssignmentsController < BaseController
    before_action :set_students, only: [:new, :create, :edit, :update, :show]
    before_action :set_sections, only: [:new, :create, :edit, :update, :show]

    def index
      @assignments = Assignment.order(created_at: :desc)
    end

    def new
      @assignment = Assignment.new
      @assignments_fte = {}
      @assignments_is_fixed = {}
    end

    def edit
      @assignment = Assignment.find(params[:id])
      @assignments_fte = @assignment.assignments_fte
      @assignments_is_fixed = @assignment.assignments_is_fixed
    end

    def create
      @assignments_fte = params[:assignments_fte] || {}
      @assignments_is_fixed = params[:assignments_is_fixed] || {}

      if params[:commit] == "Run solver"
        begin
          problem = ::IntegerLinearProgram.new(@students, @sections, @assignments_fte, @assignments_is_fixed)
          problem.solve
          @assignments_fte = problem.results
        rescue RuntimeError
          flash[:alert] = "Infeasible solution"
        end
      end

      @assignment = Assignment.create(
        assignments_fte: @assignments_fte, assignments_is_fixed: @assignments_is_fixed)
      redirect_to administrator_assignment_path(@assignment)
    end

    def update
      @assignments_fte = params[:assignments_fte] || {}
      @assignments_is_fixed = params[:assignments_is_fixed] || {}

      if params[:commit] == "Run solver"
        begin
          problem = ::IntegerLinearProgram.new(@students, @sections, @assignments_fte, @assignments_is_fixed)
          problem.solve
          @assignments_fte = problem.results
        rescue RuntimeError
          flash[:alert] = "Infeasible solution"
        end
      end

      @assignment = Assignment.create(
        assignments_fte: @assignments_fte, assignments_is_fixed: @assignments_is_fixed)
      redirect_to administrator_assignment_path(@assignment)
    end

    def show
      @assignment = Assignment.find(params[:id])
      @assignments_fte = @assignment.assignments_fte
      @assignments_is_fixed = @assignment.assignments_is_fixed

      respond_to do |format|
        format.html
        format.txt  { render 'show.txt.erb' }
        format.xlsx { render xlsx: 'show.xlsx.axlsx' }
      end
    end

    private

    def set_students
      @students = User.includes([{section_preferences: :section}, :experiences]).gtas
    end

    def set_sections
      @sections = Section.includes(
        {course: [:requirements, :department]},
        {instructor: :student_preferences}, :section_preferences)
        .with_current_term
        .where('current_enrollment >= ?', 25)
    end
  end
end

app/controllers/administrator/base_controller.rb
module Administrator
  class BaseController < ::ApplicationController
    before_filter :authenticate
    before_filter :authorize

    def authenticate
      unless signed_in?
        return redirect_to root_path, alert: "Must be logged in."
      end
    end

    def authorize
      unless current_user.is_administrator
        return redirect_to root_path, alert: "Must be an administrator."
      end
    end
  end
end

app/controllers/administrator/settings_controller.rb
module Administrator
  class SettingsController < BaseController
    def index
      @terms = Section.select("DISTINCT term").map { |s| [s.term, s.term] }
    end

    def set_current_term
      Setting.current_term = params[:current_term]
      redirect_to administrator_settings_path
    end

    def section_preferences
      @students = User.gtas
      @sections = Section.includes(:section_preferences).with_current_term

      respond_to do |format|
        format.xlsx
      end
    end

    def student_preferences
      @students = User.gtas
      @sections = Section.includes(:section_preferences).with_current_term

      respond_to do |format|
        format.xlsx
      end
    end
  end
end

app/controllers/administrator/users_controller.rb
module Administrator
  class UsersController < BaseController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /admin/users
    def index
      @users = User.all
    end

    # GET /admin/users/1
    def show
    end

    # GET /admin/users/new
    def new
      @user = User.new
    end

    # GET /admin/users/1/edit
    def edit
    end

    # POST /admin/users
    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to administrator_user_path(@user), notice: 'User was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/users/1
    def update
      if @user.update(user_params)
        redirect_to administrator_user_path(@user), notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/users/1
    def destroy
      @user.destroy
      redirect_to administrator_users_url, notice: 'User was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def user_params
        params[:user].permit(:first_name, :last_name, :email, :cc_instructor_tag, :is_administrator, :fte)
      end
  end
end

app/controllers/administrators/assignment_controller.rb
module Administrators
  class AssignmentController < BaseController

    def index
      # @students = User.where(role: "student")
      # @instructos = User.where(role: "instructor")
      
      @sections = [
        "CS 101", "CS 102", "CS 103", "CS 104", "CS 105", 
        "CS 106", "CS 107", "CS 108", "CS 109", "CS 110",
        "CS 101", "CS 102", "CS 103", "CS 104", "CS 105", 
        "CS 106", "CS 107", "CS 108", "CS 109", "CS 110",
        "CS 101", "CS 102", "CS 103", "CS 104", "CS 105", 
        "CS 106", "CS 107", "CS 108", "CS 109", "CS 110",
      ]
      @students = ["Jonah George", "Katie Gifford",  "Ty Skelton", "Tyler Hoppe",
        "JJ Carlos", "John Bourgeious", "Michael McDonald"]
    end

  end
end

app/controllers/administrators/base_controller.rb
module Administrators
  class BaseController < ::ApplicationController
    before_filter :authenticate
    before_filter :authorize

    def synchronize
      CourseCatalogSyncJob.perform_later
      redirect_to root_path
    end

    def authenticate
      unless signed_in?
        return redirect_to root_path, alert: "Must be logged in."
      end
    end

    def authorize
      unless current_user.role == "Administrator"
        return redirect_to root_path, alert: "Must be an administrator."
      end
    end
  end
end

app/controllers/administrators/pages_controller.rb
module Administrators
  class PagesController < BaseController
    def settings
    end
  end
end

app/controllers/administrators/reports_controller.rb
module Administrators
  class ReportsController < BaseController

    def student_preferences
      @students = Student.all
      @department = Department.find_by_subject_code("CS")

      respond_to do |format|
        format.xlsx
      end
    end

    def instructor_preferences
      @instructors = Instructor.all

      respond_to do |format|
        format.xlsx
      end
    end

  end
end

app/controllers/administrators/users_controller.rb
module Administrators
  class UsersController < BaseController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /admin/users
    def index
      @users = User.all
    end

    # GET /admin/users/1
    def show
    end

    # GET /admin/users/new
    def new
      @user = User.new
    end

    # GET /admin/users/1/edit
    def edit
    end

    # POST /admin/users
    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to administrators_user_path(@user), notice: 'User was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/users/1
    def update
      if @user.update(user_params)
        redirect_to administrators_user_path(@user), notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/users/1
    def destroy
      @user.destroy
      redirect_to administrators_users_url, notice: 'User was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def user_params
        params[:user].permit(:name, :email, :role)
      end
  end
end

app/views/administrator/assignments/_form.html.erb
<%= form_for [:administrator, @assignment] do |f| %>

  <%= f.submit "Run solver", class: "btn btn-warning" %>
  <%= f.submit "Save", class: "btn btn-success" %>

  <br>
  <br>

  <div class="table-responsive">
    <table class="table table-sm table-striped">
      <tr>
        <td></td>
        <% @sections.each do |section| %>
          <td>
            <span style="white-space: nowrap;"><%= section.course.label %>-<%= section.section %></span><br>
            <span style="white-space: nowrap;"><%= section.cc_instructor_tag %></span><br>
            <span style="white-space: nowrap;"><%= section.current_enrollment %> / <%= section.max_enrollment %></span>
          </td>
        <% end %>
      </tr>

      <% @students.each do |student| %>
        <tr>
          <td>
            <span style="white-space: nowrap;"><%= "#{student.full_name} (#{student.fte})" %></span>
          </td>
          <% @sections.each do |section| %>
            <td>
              <input
                type="number"
                name="assignments_fte[<%= student.id %>_<%= section.id %>]"
                value="<%= @assignments_fte["#{student.id}_#{section.id}"] || 0.0 %>"
                step=0.01
                min=0.0
                max=0.50
              />
              <label>
                <input
                  type="checkbox"
                  name="assignments_is_fixed[<%= student.id %>_<%= section.id %>]"
                  value="true"
                  <%= "checked" if @assignments_is_fixed["#{student.id}_#{section.id}"] %>
                /> Fixed
              </label>
            </td>
          <% end %>
        </tr>
      <% end %>

    </table>
  </div>
<% end %>

app/views/administrator/assignments/edit.html.erb
<%= link_to "&larr; Back to Assignments".html_safe, administrator_assignments_path %>

<h2>Edit Assignment #<%= @assignment.id %></h2>

<%= render "form" %>

app/views/administrator/assignments/index.html.erb
<h2>Assignments</h2>

<%= link_to "Create new assignment", new_administrator_assignment_path, class: "btn btn-success" %>

<br>
<br>

<table class="table table-striped">
  <thead>
    <th>Id</th>
    <th>Date</th>
    <!-- <th>Author</th> -->
  </thead>
  <% @assignments.each do |assignment| %>
    <tr>
      <td><%= link_to "Assignment ##{assignment.id}", administrator_assignment_path(assignment) %></td>
      <td><%= assignment.updated_at.to_s(:short) %></td>
      <!-- <td>Jonah George</td> -->
    </tr>
  <% end %>
</table>

app/views/administrator/assignments/new.html.erb
<%= link_to "&larr; Back to Assignments".html_safe, administrator_assignments_path %>

<h2>New Assignment</h2>

<%= render "form" %>

app/views/administrator/assignments/show.html.erb
<%= link_to "&larr; Back to Assignments".html_safe, administrator_assignments_path %>

<h2>Assignment #<%= @assignment.id %></h2>

<%= link_to "Edit", edit_administrator_assignment_path(@assignment),
  class: "btn btn-default btn-warning" %>
<%= link_to "Export to Plaintext", administrator_assignment_path(@assignment, format: "txt"),
  class: "btn btn-default btn-success" %>
<%= link_to "Export to Excel", administrator_assignment_path(@assignment, format: "xlsx"),
  class: "btn btn-default btn-success" %>

<br>
<br>

<div class="table-responsive">
  <table class="table table-sm table-striped table-bordered">
    <tr>
      <td></td>
      <% @sections.each do |section| %>
      <td>
        <span style="white-space: nowrap;"><%= section.course.label %>-<%= section.section %></span><br>
        <span style="white-space: nowrap;"><%= section.cc_instructor_tag %></span><br>
        <span style="white-space: nowrap;"><%= section.current_enrollment %> / <%= section.max_enrollment %></span>
      </td>
      <% end %>
    </tr>

    <% @students.each do |student| %>
      <tr>
        <td>
          <span style="white-space: nowrap;"><%= "#{student.full_name} (#{student.fte})" %></span>
        </td>
        <% @sections.each do |section| %>
          <td>
            <% if @assignments_fte["#{student.id}_#{section.id}"].to_f > 0 %>
              <b><%= @assignments_fte["#{student.id}_#{section.id}"] %></b>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>

  </table>
</div>

app/views/administrator/assignments/show.txt.erb
<% @students.each do |student| %>
  <%= "#{student.full_name} (#{student.fte})" %>
  <% @sections.each do |section| %>
    <% if @assignments_fte["#{student.id}_#{section.id}"] > 0 %>
      <%= "\t #{section.course.label}-#{section.section}" %> (<%= @assignments_fte["#{student.id}_#{section.id}"] %>)
    <% end %>
  <% end %>
<% end %>